# Generated by Django 5.1.6 on 2025-02-24 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='language_code',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('ru', 'Russian')], default='', max_length=7, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='paragraph',
            name='language_code',
            field=models.CharField(choices=[('en', 'English'), ('ru', 'Russian')], max_length=7, verbose_name='Language'),
        ),
    ]
