# Generated by Django 5.1.6 on 2025-02-25 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_userprofile_pbx_number'),
        ('settings', '0004_alter_categorynumenclature_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Numenclature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Количество')),
                ('ask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.userprofile', verbose_name='Заявка')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numenclature_inventory', to='settings.categorynumenclature', verbose_name='ТМЦ')),
            ],
            options={
                'verbose_name': 'ТМЦ для заявки',
                'verbose_name_plural': 'ТМЦ для заявки',
                'ordering': ['ask', 'inventory'],
            },
        ),
    ]
