# Generated by Django 5.1.6 on 2025-02-25 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_numenclature'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='numenclature',
            options={'ordering': ['inventory'], 'verbose_name': 'ТМЦ для заявки', 'verbose_name_plural': 'ТМЦ для заявки'},
        ),
        migrations.RemoveField(
            model_name='numenclature',
            name='ask',
        ),
    ]
