# Generated by Django 5.1.6 on 2025-02-24 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('massmail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emlmessage',
            name='content',
            field=models.TextField(help_text="\n    Use HTML. To specify the address of the embedded image, use {% cid_media ‘path/to/pic.png' %}.<br>\n    You can embed files uploaded to the CRM server in the ‘media/pics/’ folder or attached to this message.\n    "),
        ),
        migrations.AlterField(
            model_name='signature',
            name='content',
            field=models.TextField(help_text="\n    Use HTML. To specify the address of the embedded image, use {% cid_media ‘path/to/pic.png' %}.<br>\n    You can embed files uploaded to the CRM server in the ‘media/pics/’ folder.\n    "),
        ),
    ]
