# Generated by Django 5.1.6 on 2025-02-24 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_reminders'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryNumenclature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numenclature', models.CharField(max_length=600, unique=True, verbose_name='ТМЦ')),
            ],
            options={
                'verbose_name': 'Товарныая позиция',
                'verbose_name_plural': 'Товарные позиции',
            },
        ),
    ]
