# Generated by Django 5.1.6 on 2025-02-25 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_categorynumenclature'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorynumenclature',
            options={'verbose_name': 'Товарная позиция', 'verbose_name_plural': 'Товарные позиции'},
        ),
    ]
