# Generated by Django 5.1.6 on 2025-02-25 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_alter_categorynumenclature_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorynumenclature',
            name='amount',
            field=models.IntegerField(default=1, verbose_name='Количество'),
            preserve_default=False,
        ),
    ]
