# Generated by Django 5.1.6 on 2025-02-25 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_alter_numenclature_options_remove_numenclature_ask'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='sla',
            field=models.ManyToManyField(blank=True, null=True, to='common.numenclature', verbose_name='sla'),
        ),
    ]
